### ISSUE TITLE
Error: Failed to get exchange rate from Currency Converter API Caused by: "Query parameter not found"

### ISSUE THREAD

**Issue by wizonesolutions** [borsboom/foreign-currency-accounts-for-ynab#1]
I'm getting this error when the app tries to get currency rates. I'm seeing the same error on Windows and Mac.

```
  Getting exchange rates from API for 2019-11-11...
Error: Failed to get exchange rate from Currency Converter API
Caused by: "Query parameter not found"
```

What should I try? Is there a way to get more verbose logging?

**Comment by borsboom** [comment]
Try setting the `RUST_LOG` environment variable to `fca4ynab=debug`.  It will output the https://free.currconv.com URL it uses to try to download the rates, which may help narrow down the problem.

**Comment by wizonesolutions** [comment]
Heh, today it is fine. Perhaps it's either a rate limit thing or something that happens near midnight. Or maybe the free API was just down for maintenance. The app doesn't seem to actually do anything if it hits an error, so it seems like I can just put this on cron and not worry about the errors. I will leave this open in case it happens again, and I can catch it in time, since it might result in an improvement.

**Comment by borsboom** [comment]
The free currency converter API isn't particularly reliable.  I get 500 errors pretty frequently too, sometimes for a day or more at a time.  You can get a prepaid account where you pay by number of requests that supposedly uses a more reliable server, but I haven't tried it yet.  This tool does try to keep the number of requests minimal (one per day per budget, or less if multiple budgets use the same currencies) so the $3 minimum for the prepaid should last a long time.

**Comment by wizonesolutions** [comment]
Is there an environment variable at the moment to use the prepaid server URL?

**Comment by borsboom** [comment]
I've added support for the non-free Currency Converter API servers in [v0.1.7](https://github.com/borsboom/foreign-currency-accounts-for-ynab/releases/tag/release/0.1.7).

I'll close this issue, since I'm almost certain that the original problem was on the Currency Converter API's end.
