### ISSUE TITLE
YNAB uses non-converted values when dealing with foreign credit cards

### ISSUE THREAD

**Issue by wizonesolutions** [borsboom/foreign-currency-accounts-for-ynab#13]
Running into an issue with YNAB's handling of credit cards, even when said card is paid from a same-currency account.

Basically, I set it up with a Starting Balance of 210 (NOK). Then, today I reconciled in a payment of the same amount to it and registered it as a transfer from another NOK account. For some reason, YNAB is showing the credit card category as $210 overspent, and it deducts this from this month's balance (as it does).

I think this means that it leaves less money in my budget than is really there, since there would be an NOK adjustment for Starting Balance but not a proper adjustment for the transfer. I'm not really sure how to do a transfer, even following https://borsboom.io/foreign-currency-accounts-for-ynab/#transfers-between-currencies, that would have the correct result, either, since the amount for the difference account would still be 0.

Should I maybe just treat it as if the money came out of the blue (basically as "income to the card") and not register it as a transfer at all? Then that should just leave me with the regular fluctuation, I guess.

Or should I re-add the account as something other than a credit card so that YNAB doesn't try to be smart with it?

**Comment by wizonesolutions** [comment]
Ah: I guess this is perhaps handled because the initial inflow _returns_ money to the budget. Thus, even if I cover the shortfall, the difference should more or less turn out to be the USD value of the payment (even though it feels a little unintuitive with how YNAB presents it)?

**Comment by borsboom** [comment]
Adding a foreign currency credit card with an initial balance isn't a use case I tested before.  Just tried it, and it is definitely weird.  It would seem that it considers the difference transaction for the initial balance to be deducted from "to be balanced", which must be a side effect of how the API returns credit card initial transactions.  Ultimately it isn't possible for money to disappear to nowhere (or appear from nowhere), but sometimes YNAB can make it look that way.

At this point not sure if this is something that's possible to add a special case for, and not really sure how how that special case would treat this transaction.

**Comment by borsboom** [comment]
> Basically, I set it up with a Starting Balance of 210 (NOK). Then, today I reconciled in a payment of the same amount to it and registered it as a transfer from another NOK account. For some reason, YNAB is showing the credit card category as $210 overspent, and it deducts this from this month's balance (as it does).

Leaving aside that this is a foreign currency account, I believe this is normal behaviour.  If you make a CC payment without having budgeted for it, that is considered a shortfall.

**Comment by wizonesolutions** [comment]
Ah, right, because I entered the starting balance mid-cycle (despite not
actually having floated a balance). It's been so long since I've actually
had debt that I forgot how YNAB treated it!

But it does seem like the right thing basically happens in terms of raw
numbers.

**Comment by borsboom** [comment]
I've thought about this a bit more, and I think basically I'd need to add support for a difference account specifically for credit cards (for each currency), as well as some special casing around transfers to/from credit cards also creating corresponding transfers to/from the difference account.

**Comment by borsboom** [comment]
I've opened an work-in-progress PR to try out my solution above: #14.  You can grab binaries from the artifacts link (top-right) in [build 178](https://dev.azure.com/borsboom/foreign-currency-accounts-for-ynab/_build/results?buildId=178).

I didn't end up needing the special case for transfers, since this ends up being handled by two adjustment transactions in the respective difference accounts (one inflow, the other an outflow for the same amount).

**Comment by borsboom** [comment]
Released in [v0.1.10](https://github.com/borsboom/foreign-currency-accounts-for-ynab/releases/tag/release/0.1.10).

**Comment by wizonesolutions** [comment]
Seems to work well!

**Comment by james-rose** [comment]
Question on this one:  if we have existing foreign credit accounts already using the initial difference account, when we switch these existing accounts to this new credit card difference account, will that cause problems?

**Comment by borsboom** [comment]
It shouldn't cause problems.  You'll end up with Adjustment transactions in both the pre-existing debit and new credit difference accounts, which will cancel each other out.

**Comment by james-rose** [comment]
ok, thanks
