### ISSUE TITLE
Error: Could not find account for transaction

### ISSUE THREAD

**Issue by james-rose** [borsboom/foreign-currency-accounts-for-ynab#19]
I got this error after deleting a YNAB bank account.  This has happened in the past too, and the only way that I found to get rid of the issue was to delete the DB file, create a new diff account and start over.   I was hoping you had a less drastic way to make this error go away.

The error:
Processing latest transactions...
Error: Could not find account for transaction

**Comment by borsboom** [comment]
I've opened PR #20 that should hopefully fix this for you.  You can [download binaries with the fix from this link](https://dev.azure.com/borsboom/foreign-currency-accounts-for-ynab/_build/results?buildId=201&view=artifacts&type=publishedArtifacts) (note: Linux and macOS binaries are there, but Windows is still in progress -- if you need that, check back in ten minutes or so).

**Comment by james-rose** [comment]
Excellent, that fixed it!

**Comment by borsboom** [comment]
Released in [v0.1.9](https://github.com/borsboom/foreign-currency-accounts-for-ynab/releases/tag/release/0.1.9).
