### ISSUE TITLE
Feature request: default split transactions to parent transaction payee

### ISSUE THREAD

**Issue by wizonesolutions** [borsboom/foreign-currency-accounts-for-ynab#2]
As per your request in the YNAB thread, opening a feature request. Reference: https://support.youneedabudget.com/t/h44n4m?r=x19kwc

**Comment by borsboom** [comment]
I've opened a PR with this change: #3.

**Comment by borsboom** [comment]
@wizonesolutions You can grab a new binary by clicking on **Artifacts** (top-right) [in the build](https://dev.azure.com/borsboom/foreign-currency-accounts-for-ynab/_build/results?buildId=154).  Assuming this works for you, I'll make a new release including the change soon.

**Comment by wizonesolutions** [comment]
Cool, will try it when I next have a split.

**Comment by borsboom** [comment]
Released in [v0.1.5](https://github.com/borsboom/foreign-currency-accounts-for-ynab/releases/tag/release/0.1.5).

**Comment by wizonesolutions** [comment]
Works great!
