### ISSUE TITLE
Support for scheduled transactions

### ISSUE THREAD

**Issue by wizonesolutions** [borsboom/foreign-currency-accounts-for-ynab#4]
I'm wondering if it would make sense to support scheduled transactions.

I guess that estimating using the most current rate would make sense, meaning that there'd be adjustment transactions every day until the transaction actually posted to the account.

The main purpose would be so that YNAB would be a little more accurate when flagging budget categories, e.g.:

![image](https://user-images.githubusercontent.com/344116/68621311-b171fb80-04cf-11ea-80c7-4f24688f8dcd.png)

Maybe you have a different way of dealing with these or turn off the feature?

**Comment by borsboom** [comment]
Unfortunately the YNAB API doesn't have a way to create or edit scheduled transactions, so I don't think it's possible to handle these at the moment (even if it were possible to guess future exchange rates).  As it stands, this tool is good good at dealing with transactions that have happened, but doesn't really help you out with future transactions.

It would also be nice if, when you enter a new transaction, you could see the total converted amount that will be taken from the budget category.  Currently, you have to estimate whether you actually have enough money in the category to cover the transaction.

**Comment by wizonesolutions** [comment]
Ah, that makes sense. This is potentially something we could handle with a client-side browser extension that talked to a web service backed by fca4ynab, or similar. I'll close this since the API doesn't support it anyway.
