### ISSUE TITLE
Feature request: allow to put currency tag at end of account name

### ISSUE THREAD

**Issue by james-rose** [borsboom/foreign-currency-accounts-for-ynab#6]
There's not much space for the name of an account in the YNAB account bar, so it gets truncated after you add the currency tag (<USD> here):
<img width="208" alt="image" src="https://user-images.githubusercontent.com/2235103/68943765-634d4880-07ac-11ea-8dc2-6e5a914e08df.png">
I would suggest the ability to add the tag at the end of the account name, so that more of the account name gets displayed.

**Comment by borsboom** [comment]
You can put it at the end, in the middle, or even in the account notes.  From the docs:

> Put the three-letter currency code in angle brackets anywhere in the account’s nickname or notes.

**Comment by james-rose** [comment]
I’d missed that.  Thanks.
